version: "3.8"

services:
  fetch_evaluation_filtered:
    image: python:3.11
    container_name: fetch_evaluation_filtered
    volumes:
      - adobevfr_filtered:/data
      - ~/.config/rclone:/root/.config/rclone:ro
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e

        echo "Creating target directory..."
        mkdir -p /data/font-detector/evaluation_filtered

        echo "Installing rclone..."
        apt-get update && apt-get install -y rclone

        echo "Syncing data into /data/font-detector/evaluation_filtered..."
        rclone sync chi_tacc:object-persist-project41/evaluation_filtered /data/font-detector/evaluation_filtered --progress

        echo "Done syncing."
    restart: "no"

volumes:
  adobevfr_filtered:
    external: true
