FROM python:3.11

WORKDIR /app

COPY extract_adobevfr.py .
COPY adobevfr_dataset.py .
COPY fastapi_pt/fontsubset.txt /app/fontsubset.txt
COPY adobevfr_dataset.py .

RUN pip install --no-cache-dir numpy pillow tqdm opencv-python-headless

ENTRYPOINT ["python", "extract_adobevfr.py"]
