version: "3.8"

services:
  fetch_evaluation_filtered:
    image: python:3.11
    container_name: fetch_evaluation_filtered
    volumes:
      - adobevfr_filtered:/data
      - /home/cc/.config/rclone:/root/.config/rclone:ro
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -ex

        echo "Create target directory"
        mkdir -p /data/font-detector/evaluation_filtered

        echo "Install rclone"
        apt-get update && apt-get install -y rclone

        echo "List contents before sync:"
        rclone ls chi_tacc:object-persist-project41/datasets/adobevfr/evaluation_filtered | head

        echo "Starting sync..."
        rclone sync chi_tacc:object-persist-project41/datasets/adobevfr/evaluation_filtered /data/font-detector/evaluation_filtered --progress

        echo "Done syncing."
        ls -lh /data/font-detector/evaluation_filtered | head
    restart: "no"

volumes:
  adobevfr_filtered:
    external: true
