version: '3.8'

services:
  synth-gen:
    build:
      context: ..
      dockerfile: docker/Dockerfile.synthetic
    volumes:
      - /mnt/block100:/data
    command:
      - python3
      - generate_synthetic_images.py
      - --fonts_dir
      - /data/GoogleFonts
      - --out_dir
      - /data/Synthetic
      - --images_per_font
      - "1000"
