# Helps run load and run the script generate_synthetic_images onto a docker
FROM python:3.11-slim

WORKDIR /workspace

# Install Pillow
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    && pip install pillow \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY generate_synthetic_images.py .

ENTRYPOINT ["python3", "generate_synthetic_images.py"]
